version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: fastapi_postgres
    environment:
      POSTRES_USER: serhii
      POSTGRES_PASSWORD: secret01
      POSTGRES_DB: rest_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: